version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: udaykirane98/mysql:v1
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
    networks:
    - expense
  backend:
    image: udaykirane98/backend:v1
    container_name: backend
    command: sh -c "sleep 10 && node /opt/server/index.js"
    depends_on:
    - mysql
    networks:
    - expense

  frontend:
    image: udaykirane98/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
    networks:
    - expense
